name: "OneWire Server"
description: "OneWire Server"
version: "1.0.2"
slug: "owserver"
url: https://github.com/stephenhouser/hassio-addons/tree/master/owserver
ports:
  4304/tcp: 4304 
ports_description:
  4304/tcp: OneWire Server Network Interface
usb: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
